### ISSUE TITLE
option to "launch" in macpass to open the entry in macpass

### ISSUE THREAD

**Issue by zeltak** [vabatta/alfred-keepass#1]
Hi!

 Thx so much for working on this amazing project!

would be great to add an option in alfred to to "launch" in macpass to open the entry in macpass
that way you can view the full data in the entry

thx!

Z

**Comment by vabatta** [comment]
You can use triggers and dispatches of the Alfred workflow to an applescript to achieve this, as the script itself can't access or control macpass.
